name = "mirrorbot-solver"
main = "src/index.ts"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

account_id = "2069a0e7348e495373ef64e17cc6ecc1"

[browser]
binding = "BROWSER"
